# Autogenerated wrapper script for PokerIsomorphism_jll for aarch64-apple-darwin
export libHandIsomorphism

JLLWrappers.@generate_wrapper_header("PokerIsomorphism")
JLLWrappers.@declare_library_product(libHandIsomorphism, "@rpath/libHandIsomorphism.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libHandIsomorphism,
        "lib/libHandIsomorphism.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
