# Autogenerated wrapper script for PokerIsomorphism_jll for i686-w64-mingw32
export libHandIsomorphism

JLLWrappers.@generate_wrapper_header("PokerIsomorphism")
JLLWrappers.@declare_library_product(libHandIsomorphism, "libHandIsomorphism.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libHandIsomorphism,
        "bin\\libHandIsomorphism.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
